# Explanation of data

## 1-total_bill:

Description: The total amount of the bill (in dollars) for the meal, including the cost of food and drinks.
Data Type: Float
Example: 16.99
## 2-tip:

Description: The amount of the tip (in dollars) given by the customer to the server.
Data Type: Float
Example: 1.01
## 3-sex:

Description: The gender of the person who paid for the meal.
Data Type: Categorical (string)
Possible Values: 'Male', 'Female'
Example: 'Female'
## 4-smoker:

Description: Indicates whether there were smokers in the party.
Data Type: Categorical (string)
Possible Values: 'Yes', 'No'
Example: 'No'
## 5-day:

Description: The day of the week when the meal was served.
Data Type: Categorical (string)
Possible Values: 'Thur' (Thursday), 'Fri' (Friday), 'Sat' (Saturday), 'Sun' (Sunday)
Example: 'Sun'
## 6-time:

Description: The time of day when the meal was served.
Data Type: Categorical (string)
Possible Values: 'Lunch', 'Dinner'
Example: 'Dinner'
## 7-size:

Description: The number of people in the party.
Data Type: Integer
Example: 2

In [56]:
import pandas as pd 
import numpy as np 
import seaborn as sns

## Load the dataset

In [57]:
df=pd.read_csv("tips.csv")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

## Display the first few rows

In [58]:
df.head() #defaut=5

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

## Question 1: What is the average total bill amount?

In [59]:
df["total_bill"].mean()

np.float64(19.78594262295082)

## Question 2: How many records are in the dataset?

In [60]:
df.count()

total_bill    244
tip           244
sex           244
smoker        244
day           244
time          244
size          244
dtype: int64

## Question 3: What is the total amount of tips given by male customers?

In [61]:
df[df["sex"]=="Male"].agg({"tip":"sum"})

#df.groupby("sex").agg({"tip":"sum"})  #to check the result

tip    485.07
dtype: float64

## Question 4: What is the maximum tip given?

In [62]:
df["tip"].max()

np.float64(10.0)

## Question 5: What are the unique days on which the tips were recorded?

In [63]:
display(df.groupby("tip").agg({"day":"unique"}))
display(df["day"].unique())
display(df["day"].value_counts())

               day
tip
1.00    [Sat, Fri]
1.01         [Sun]
1.10         [Sat]
1.17         [Sat]
1.25   [Sat, Thur]
...            ...
6.70        [Thur]
6.73         [Sat]
7.58         [Sat]
9.00         [Sat]
10.00        [Sat]

[123 rows x 1 columns]

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

## Question 6: What is the average tip amount given by female customers?

In [64]:
df[df["sex"]=="Female"].agg({"tip":"mean"})

tip    2.833448
dtype: float64

## Question 7: How many customers are non-smokers?

In [65]:
sum(df["smoker"]=="No")

151

## Question 8: What is the average total bill for dinners?

In [66]:
df["total_bill"].mean()

np.float64(19.78594262295082)

## Question 9: What is the smallest size of a group recorded?

In [67]:
df.min

<bound method DataFrame.min of      total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]>

## Question 10: What is the standard deviation of the total bill amounts?

In [68]:
display(df["total_bill"].std()) # By default std dev is for sample
display(df.total_bill.std(ddof=1)) #For Sample
display(df.total_bill.std(ddof=0)) # For Population

np.float64(8.902411954856856)

np.float64(8.902411954856856)

np.float64(8.884150577771132)

## Question 11: How many male smokers are there compared to female smokers?

In [69]:
display(df.groupby(["smoker","sex"]).agg({"smoker":"count"})) # Comparison for smokers and non smokers between male and femal


print("-"*30)
print("Using value.counts(): ")
display(df[df["smoker"]=="Yes"]["sex"].value_counts()) # only Smokers in male and femal


print("-"*30)
print("Another Way Using groupby() and size() ")
display(df.groupby(df[df["smoker"]=="Yes"]["sex"]).size())

               smoker
smoker sex
No     Female      54
       Male        97
Yes    Female      33
       Male        60

------------------------------
Using value.counts():

sex
Male      60
Female    33
Name: count, dtype: int64

------------------------------
Another Way Using groupby() and size()

sex
Female    33
Male      60
dtype: int64

## Question 12: How much more do male customers tip on average than female customers?

In [70]:
#df.groupby("sex").agg({"tip":"mean"})

display(df.groupby("sex").agg({"tip":"mean"})) # Comparison between male and female average tip 

print("-"*30)
male_tip=df[df["sex"]=="Male"].agg({"tip":"mean"})
female_tip=df[df["sex"]=="Female"].agg({"tip":"mean"})
print("Average Male Tip - Average Female Tip :")
print(male_tip-female_tip)

print("-"*30)
print("Average Male Tip - Average Female Tip :")
display(df[df["sex"]=="Male"]["tip"].mean()-df[df["sex"]=="Female"]["tip"].mean()) # tip average difference

             tip
sex
Female  2.833448
Male    3.089618

------------------------------
Average Male Tip - Average Female Tip :
tip    0.25617
dtype: float64
------------------------------
Average Male Tip - Average Female Tip :

np.float64(0.25616955853283585)

## Question 13: What is the median tip amount given by customers on Thursdays?

In [71]:
display(df[df["day"]=="Thur"].agg({"tip":"median"}))

display(df[df["day"]=="Thur"]["tip"].median())

tip    2.305
dtype: float64

np.float64(2.3049999999999997)

## Question 14: What is the total tip amount given by customers on Friday?

In [72]:
display(df[df["day"]=="Fri"].agg({"tip":"sum"}))

display(df[df["day"]=="Fri"]["tip"].sum())

tip    51.96
dtype: float64

np.float64(51.959999999999994)

## Question 15: What is the average tip amount for non-smokers during dinner time?

In [73]:
display(df[(df["smoker"]=="No")& (df["time"]=="Dinner")]["tip"].mean())


print("-"*30)
print("Another Way:")
# group data by "smoker" & "time" then calculate the mean of tip for each group 
# filtered to these values "No" (non smoker), and "Dinner" (time)
display(df.groupby(["smoker","time"])["tip"].mean().loc["No","Dinner"])

np.float64(3.1268867924528303)

------------------------------
Another Way:

np.float64(3.1268867924528303)

## Question 17: What is the most common day for customers to visit the restaurant?

In [74]:
display(df["day"].value_counts().idxmax()) # value_count counts occurance in "day" the idxmax() returns the most frequent one

df["day"].mode()[0] # Get it Directly

'Sat'

'Sat'

## Question 18: What is the range of tip amounts for female customers?

In [75]:
max_Fem_tip=df[df["sex"]=="Female"]["tip"].max()
min_Fem_tip=df[df["sex"]=="Female"]["tip"].min()

display(max_Fem_tip-min_Fem_tip) # Range=Max-Min

np.float64(5.5)

## Question 19: Calculate the total bill for parties of 5 or more people (size).

In [76]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [77]:
df[df["size"]>=5]["total_bill"].sum()

np.float64(289.65999999999997)

## Question 20: What is the highest total bill recorded during lunch?

In [78]:
df[df["time"]=="Lunch"]["total_bill"].max()

np.float64(43.11)

## Question 21: How many customers visited the restaurant on weekends (Saturday and Sunday) and ordered a total bill of more than $20?



```
# Hint isin ()

```

In [79]:
df[df["day"].isin(["Sat","Sun"]) & (df["total_bill"]>20)]["size"].sum()

np.int64(235)